name: GraalVM Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        graalvm: [ '21.0.0.2' ]
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.graalvm }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: ${{ matrix.graalvm }}
        java: 'java11'
    - name: Install native-image plugin
      run: gu install native-image
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: ./gradlew :omnij-cli:nativeImage --scan --info --stacktrace
    - name: Upload omnij-consensus-tool as artifact
      uses: actions/upload-artifact@v2
      with:
        name: omnij-consensus-tool-${{ matrix.os }}
        path: omnij-cli/build/omnij-consensus-tool
